# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6730a2fb-d705-4c09-aeb2-2a6c9939e8db";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd:3" "noatime" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/4d55f0f1-deab-4042-ad59-27148d344841";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6730a2fb-d705-4c09-aeb2-2a6c9939e8db";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6730a2fb-d705-4c09-aeb2-2a6c9939e8db";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd:3" "noatime"  ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/6730a2fb-d705-4c09-aeb2-2a6c9939e8db";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/6730a2fb-d705-4c09-aeb2-2a6c9939e8db";
      fsType = "btrfs";
      options = [ "subvol=log" "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0BD3-F3F8";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp58s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
